name: Great Learning Action

on:
  push:
    branches: [ main ]

jobs:
  run_flask:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
      - run: sudo apt-get install python3-distutils
      - run: pip install -r requirements.txt